from typing import Protocol

from src.db.models import Sender, Ticket, Message


class SenderRepo(Protocol):
    async def get_by_email(self, email: str) -> Sender | None: ...
    async def get_by_id(self, sender_id: int) -> Sender | None: ...
    async def add(self, sender: Sender) -> Sender: ...


class TicketRepo(Protocol):
    async def add(self, ticket: Ticket) -> Ticket: ...
    async def get_owned(self, ticket_id: int, sender_id: int) -> Ticket | None: ...
    async def list_by_sender(self, sender_id: int) -> list[Ticket]: ...


class MessageRepo(Protocol):
    async def add(self, message: Message) -> Message: ...
    async def list_for_ticket(self, ticket_id: int) -> list[Message]: ...
